Institutions events page redirect
eciis/web pull request #1468
Opened 2019-02-20 12:35 UTC by pedroespindula

**Feature/Bug description:** Institution events whas redirecting to desktop version.

**Solution:** Add institutionKey as a query param in events state and use it as a filter in events state.

**TODO/FIXME:** n/a

2019-02-20 13:06 UTC, raonismaneoto requested changes

2019-02-20 13:06 UTC, raonismaneoto commented on frontend/app.js
> +                url: "/events?institutionKey",
to pass a param like that use the pattern we're used to do in the states' definition. There is an example two states below this one.

2019-02-20 13:06 UTC, raonismaneoto commented on frontend/event/eventController.js
> +                    eventCtrl.institution = institution;
eventCtrl.institution = new Institution(institution)

2019-02-20 13:39 UTC, raonismaneoto approved these changes

2019-02-21 14:45 UTC, JuliePessoa requested changes

2019-02-21 14:45 UTC, JuliePessoa commented on frontend/app.js
> +                },
comma?

2019-02-21 18:09 UTC, JuliePessoa approved these changes

2019-02-21 18:10 UTC, merged