Fix css of info admins
eciis/web pull request #1473
Opened 2019-02-20 15:04 UTC by MaianaB

**Feature/Bug description:** The admin information view was broken

**Solution:** Fiz using css.

![captura de tela de 2019-02-20 11-57-20](https://user-images.githubusercontent.com/18709274/53100959-8ee61f80-3507-11e9-91a1-8732de3eafb7.png)

**TODO/FIXME:** n/a

2019-02-20 17:20 UTC, raonismaneoto approved these changes

2019-02-20 18:21 UTC, JuliePessoa requested changes
it should have blank space between the admin and the next admin.
![image](https://user-images.githubusercontent.com/7011394/53114667-18571b00-3523-11e9-90fe-ba6ad0881efa.png)

2019-02-21 11:08 UTC, pedroespindula approved these changes

2019-02-25 13:09 UTC, JuliePessoa approved these changes

2019-02-25 13:09 UTC, merged