Manage members page for mobile
eciis/web pull request #1477
Opened 2019-02-21 12:28 UTC by ruanres

**Feature/Bug description:** Design Model
![mm-model](https://user-images.githubusercontent.com/13683704/53169044-f01afb00-35ba-11e9-8446-28e395a13a81.gif)

**Solution:** Page created

![mm-page](https://user-images.githubusercontent.com/13683704/53169079-07f27f00-35bb-11e9-85bb-c4c42afa8d50.gif)

![mm-devices](https://user-images.githubusercontent.com/13683704/53169083-0aed6f80-35bb-11e9-99b3-07565c3675e5.gif)

**TODO/FIXME:** n/a

2019-02-21 12:53 UTC, pedroespindula requested changes

2019-02-21 12:53 UTC, pedroespindula commented on frontend/utils/clickableCard/clickableCard.component.js
> +(()=> {
Change to function

2019-02-21 12:53 UTC, pedroespindula commented on frontend/utils/clickableCard/clickableCard.component.js
> +        clickableCardCtrl.isOpen = false;
Define onInit with lodash defaults receiving isOpen as a binding will increase clickableCard component flexibility

2019-02-21 12:53 UTC, pedroespindula commented on frontend/utils/clickableCard/clickable_card.html
> +    <md-toolbar  ng-click="clickableCardCtrl.onClick()" class="clickable-card__toolbar">
Can you use a div instead of md-toolbar?

2019-02-21 12:53 UTC, pedroespindula commented on frontend/utils/clickableCard/clickable_card.html
> +        <span class="clickable-card__title"> {{ clickableCardCtrl.title}} </span>
What happens when title is too big for screen?

2019-02-21 12:54 UTC, pedroespindula commented
Also, merge with responsive and add white toolbar

2019-02-21 13:01 UTC, raonismaneoto requested changes

2019-02-21 13:01 UTC, raonismaneoto commented on frontend/institution/management_members_mobile.css
> +/* Send events section */
you mean send invites section?

2019-02-21 13:03 UTC, raonismaneoto reviewed
You want to merge it into responsive, right?

2019-02-21 17:04 UTC, JuliePessoa commented on frontend/utils/clickableCard/clickableCard.component.js
> +            Object.assign(clickableCardCtrl, {
you can use lodash defaults too.

2019-02-28 18:22 UTC, JuliePessoa requested changes

2019-02-28 18:22 UTC, JuliePessoa commented on frontend/institution/managementMembersController.js
> +        manageMemberCtrl.getMembersDeleteBtn = (event, member) => {
jsdoc for all functions

2019-02-28 18:22 UTC, JuliePessoa commented on frontend/utils/clickableCard/clickableCard.component.js
> +        clickableCardCtrl.onClick = () => {
jsdoc

2019-02-28 18:22 UTC, JuliePessoa commented on frontend/utils/entityShowcase/entityShowcase.component.js
> +        entityShowcaseCtrl.showIconBtn = iconBtn => {
jsdoc

2019-02-28 18:40 UTC, JuliePessoa reviewed
- The pendent adm is not showing, when transferring 
![image](https://user-images.githubusercontent.com/7011394/53589562-752f8280-3b6e-11e9-96b9-2bc7ba5c67c4.png)


- Green ball, showing that has new invites
![image](https://user-images.githubusercontent.com/7011394/53589491-4addc500-3b6e-11e9-9113-c614e22e51dd.png)

- Dialog of removing a member
![image](https://user-images.githubusercontent.com/7011394/53589519-60eb8580-3b6e-11e9-80a4-bdbe96db020a.png)

2019-02-28 18:40 UTC, JuliePessoa commented on frontend/utils/clickableCard/clickable_card.html
> +        <md-icon id="clickable-card__icon--end">{{ clickableCardCtrl.isOpen ? 'arrow_drop_up' : 'arrow_drop_down' }}</md-icon>
use the right green color. #84C45E

2019-03-01 13:55 UTC, ruanres commented
> * The pendent adm is not showing, when transferring
>   ![image](https://user-images.githubusercontent.com/7011394/53589562-752f8280-3b6e-11e9-96b9-2bc7ba5c67c4.png)
> * Green ball, showing that has new invites
>   ![image](https://user-images.githubusercontent.com/7011394/53589491-4addc500-3b6e-11e9-9113-c614e22e51dd.png)
> * Dialog of removing a member
>   ![image](https://user-images.githubusercontent.com/7011394/53589519-60eb8580-3b6e-11e9-80a4-bdbe96db020a.png)

2019-03-01 14:23 UTC, JuliePessoa approved these changes

2019-03-01 14:34 UTC, raonismaneoto approved these changes

2019-03-01 14:41 UTC, pedroespindula requested changes

2019-03-01 14:41 UTC, pedroespindula commented on frontend/utils/clickableCard/clickableCard.component.js
> +    .component("clickableCard", {
jsdoc

2019-03-01 14:41 UTC, pedroespindula commented on frontend/utils/searchField/searchField.component.js
> +    .component('searchField', {
jsdoc

2019-03-06 14:06 UTC, pedroespindula approved these changes

2019-03-06 14:14 UTC, merged