Edit expired event
eciis/web pull request #1493
Opened 2019-02-28 13:36 UTC by MaianaB

**Feature/Bug description:** Before when edit expired event the user could edit description and schedule, and while editing youtube link if it is invalid remove all.

**Solution:** Added disable for cases the can't edit after the deadline.
Create a directive to verify if the youtube link is valid without set value to undefine when is an invalid link.

**TODO/FIXME:** n/a

2019-02-28 14:13 UTC, ruanres approved these changes

2019-02-28 17:49 UTC, JuliePessoa requested changes

2019-02-28 17:49 UTC, JuliePessoa commented on frontend/event/create_event.html
> +                                ng-change="createEventCtrl.changeUrlLink(usefulLink, createEventCtrl.usefulLinks)"/>
why removed the type url?

2019-02-28 17:49 UTC, JuliePessoa commented on frontend/event/create_event.html
> +                                ng-change="createEventCtrl.changeUrlLink(usefulLink, createEventCtrl.usefulLinks)"/>
it is possible to put any string and save it, even if its not a link

2019-03-01 12:29 UTC, JuliePessoa approved these changes

2019-03-01 12:29 UTC, merged