Changing the way the search result is shown
eciis/web pull request #1494
Opened 2019-02-28 13:40 UTC by raonismaneoto

**Feature/Bug description:**
The way the search's result was being shown wasn't matching with the designer's specification

**Solution:**

![screenshot from 2019-02-28 10-34-49](https://user-images.githubusercontent.com/23387866/53570375-16a1de80-3b45-11e9-9cd9-ec20ac5fdb05.png)

![screenshot from 2019-02-28 10-35-10](https://user-images.githubusercontent.com/23387866/53570381-186ba200-3b45-11e9-8293-ee91a20f2e2b.png)

**TODO/FIXME:** n/a

2019-02-28 16:05 UTC, JuliePessoa requested changes
- Result institutions are being marked "Novo cadastro"
- Address and image is not showing
- Try to fix the icon resize problem

2019-02-28 16:05 UTC, JuliePessoa commented on frontend/search/search_mobile.html
> +        <div class="registered-institutions-container" ng-if="searchCtrl.institutions.length > 1" style="margin-top: -1px; margin-bottom: 5px;">
move style

2019-02-28 16:05 UTC, JuliePessoa commented on frontend/search/search_mobile.html
> +                institution="institution" user="searchCtrl.user" style="margin-top: 10px;">
move style

2019-02-28 16:05 UTC, JuliePessoa commented on frontend/search/search_mobile.html
> +                user="searchCtrl.user" style="border-style: solid; border-width: 0.5px 0px 0px 0.5px; border-color: white;">
move style

2019-02-28 16:05 UTC, JuliePessoa commented on frontend/search/search_mobile.html
> +        <div ng-if="searchCtrl.institutions.length === 0" style="margin-top: 1em; margin-left: auto; margin-right: auto;">
move style

2019-02-28 16:05 UTC, JuliePessoa commented on frontend/search/search_mobile.html
> +        <div ng-if="searchCtrl.institutions.length === 0" style="margin-top: 1em; margin-left: auto; margin-right: auto;">
use empty card component

2019-02-28 16:05 UTC, JuliePessoa commented on frontend/search/search_mobile.html
> +    <div class="search-mobile-options-title" id="search-title">
font-size bigger than it should

2019-02-28 16:05 UTC, JuliePessoa commented on frontend/search/search_mobile.html
> +    <div class="search-mobile-options-title" id="search-title">
margin top and bottom should be the same

![image](https://user-images.githubusercontent.com/7011394/53579780-f3812a00-3b58-11e9-8f93-b948f8bb392d.png)

2019-02-28 16:05 UTC, JuliePessoa commented on frontend/search/search_mobile.html
> +        <div ng-if="searchCtrl.institutions.length === 1">
Margin-left and rigth of the card content is bigger than it should.

![image](https://user-images.githubusercontent.com/7011394/53579881-2deac700-3b59-11e9-91bf-beec8de229e1.png)

2019-03-01 14:26 UTC, JuliePessoa approved these changes

2019-03-01 14:30 UTC, MaianaB approved these changes

2019-03-01 14:35 UTC, merged