Fixed empty poll option on mobile larger screens
eciis/web pull request #1496
Opened 2019-02-28 19:59 UTC by JuliePessoa

**Feature/Bug description:** 
On mobile larger screens like iphone 6/7/8 plus, polls with only two options fulfilled were posted with the third option empty.
It occurred because the code was removing an object array while was iterating in the same reference.
So what happened, the array contained 5 objects: [{"text"},{"text"},{""},{""},{""}].
Iterating over the array, every time it finds an empty object it was removed, but there were 3 empty equal objects and was the same referenced array.
On third iteration, the index = 2 , empty object removed. result array: [{"text"},{"text"},{""},{""}].
Next iteration, index = 3, so object 4 removed. result array: [{"text"},{"text"},{""}].
Theres no next iteration because theres no object on 4 index. That said, always would last one empty object.

**Bug screenshot**
![image](https://user-images.githubusercontent.com/7011394/53593866-6a79eb00-3b78-11e9-9be6-9ce15801f154.png)

**Solution:** 
Changed the way objects were removed using array.filter();

2019-02-28 20:02 UTC, JuliePessoa commented
Fixes #1471

2019-03-01 12:19 UTC, pedroespindula approved these changes

2019-03-01 12:25 UTC, raonismaneoto approved these changes

2019-03-01 12:26 UTC, raonismaneoto requested changes
Isnt there any tests for that function?

2019-03-01 13:06 UTC, raonismaneoto approved these changes

2019-03-01 13:16 UTC, merged