Frontend send email state
eciis/web pull request #1497
Opened 2019-03-01 13:40 UTC by pedroespindula

**Feature/Bug description:** Adds send current state link email feature to frontend.

**Solution:** Create a service that has a function to show a dialog when the page should be viewed on desktop.

- Dialog:
![localhost_8081_events iphone 6_7_8 plus](https://user-images.githubusercontent.com/38431219/53641588-3c46ea80-3c0e-11e9-9abc-9319f554d0c9.png)

**TODO/FIXME:** n/a

2019-03-06 13:03 UTC, JuliePessoa requested changes

2019-03-06 13:03 UTC, JuliePessoa commented on frontend/email/EmailService.js
> +        emailService.sendStateLink = (stateLink) => {
jsdoc

2019-03-06 13:03 UTC, JuliePessoa commented on frontend/email/stateLinkRequest/StateLinkRequestService.js
> +        StateLinkRequestService.showLinkRequestDialog = (stateLink, previousState) => {
jsdoc

2019-03-07 13:18 UTC, JuliePessoa approved these changes

2019-03-07 14:10 UTC, Luiz-FS requested changes

2019-03-07 14:10 UTC, Luiz-FS commented on frontend/utils/urlConstants.js
> +    angular.module("app").constant('URL_CONSTANTS', {
Use Config.FRONTEND_URL to get the correct URL

2019-03-07 14:57 UTC, Luiz-FS approved these changes

2019-03-07 18:41 UTC, merged