Improving events page mobile
eciis/web pull request #1511
Opened 2019-03-07 18:59 UTC by tiagolimpe

**Feature/Bug description:** Redesigning the events page on mobile devices to show different the events without pictures and deleted events.

**Solution:** 
![selection_042](https://user-images.githubusercontent.com/20300259/53981723-e84a7300-40f1-11e9-9d11-35bec1089ab8.png)

**TODO/FIXME:** n/a

2019-03-07 19:29 UTC, JuliePessoa requested changes

2019-03-07 19:29 UTC, JuliePessoa commented on frontend/event/events_mobile.html
>                  <md-card>
create an "event-card" component

2019-03-07 19:29 UTC, JuliePessoa commented on frontend/event/events_mobile.html
> +                    <div ng-if="event.state === 'deleted'" class="event-preview-image md-card-image"
create an canceled event header component

2019-03-07 19:35 UTC, brobsc requested changes

2019-03-07 19:35 UTC, brobsc commented on frontend/event/events_mobile.html
> +                        <md-icon class="event-canceled-icon">highlight_off</md-icon>
The cancelled icon looks out of place and overlaps with text on mobile

2019-03-07 20:51 UTC, Luiz-FS requested changes

2019-03-07 20:51 UTC, Luiz-FS commented on frontend/event/events_mobile.html
> +  <md-fab-speed-dial ng-if="!eventCtrl.institutionKey"
Why move?

2019-03-08 12:27 UTC, JuliePessoa approved these changes

2019-03-08 17:25 UTC, brobsc approved these changes

2019-03-08 19:15 UTC, Luiz-FS approved these changes

2019-03-08 20:53 UTC, merged