Create filter by institution in events page
eciis/web pull request #1514
Opened 2019-03-08 13:07 UTC by Luiz-FS

**Feature/Bug description:** Create Event Filter Screen by Institution

**Solution:** ...

![localhost_8081_events galaxy note ii](https://user-images.githubusercontent.com/18005317/54030070-36f71c00-4189-11e9-9ef6-2744edd31be4.png)

**TODO/FIXME:** n/a

2019-03-08 13:24 UTC, raonismaneoto requested changes

2019-03-08 13:24 UTC, raonismaneoto commented on frontend/event/filterEvents/filterEventByInstitution.component.js
> +(function() {
test the functions

2019-03-08 16:46 UTC, JuliePessoa requested changes

2019-03-08 16:46 UTC, JuliePessoa commented on frontend/event/eventController.js
> +            eventCtrl.isFiltering = false;
use the function below

2019-03-08 16:46 UTC, JuliePessoa commented on frontend/event/eventController.js
> +        eventCtrl.confirmFilter = function confirmFilter() {
jsdoc

2019-03-08 16:46 UTC, JuliePessoa commented on frontend/event/eventController.js
> +        eventCtrl.cancelFilter = function cancelFilter() {
jsdoc

2019-03-08 16:46 UTC, JuliePessoa commented on frontend/event/events_mobile.html
> +
remove blank line

2019-03-08 16:46 UTC, JuliePessoa commented on frontend/event/filterEvents/filter_events_by_institution.html
> +        <md-button style="color: white; background-color: #7F7F7F;" ng-click="filterCtrl.cancel()">CANCELAR</md-button>
move style

2019-03-08 20:01 UTC, JuliePessoa approved these changes

2019-03-11 16:26 UTC, raonismaneoto approved these changes

2019-03-11 17:22 UTC, merged