Add CreateInvitedInstitutionController
eciis/web pull request #1516
Opened 2019-03-08 19:57 UTC by brobsc

**Feature/Bug description:** A new controller is necessary for the new mobile design on creating invited institutions.

**Solution:** Add the new controller, based on previous (desktop) controller.

**TODO/FIXME:** n/a

2019-03-08 20:46 UTC, JuliePessoa requested changes

2019-03-08 20:46 UTC, JuliePessoa commented on frontend/test/specs/institution/createInvitedInstitutionSpec.js
> +    // httpBackend.flush();
commented?

2019-03-08 20:46 UTC, JuliePessoa commented on frontend/test/specs/institution/createInvitedInstitutionSpec.js
> +      spyOn(institutionService, 'getInstitution').and.callFake(() => {
couldn't just do` .callFake(() => $q.when(emptyInstitution)) `?

2019-03-08 20:46 UTC, JuliePessoa commented on frontend/test/specs/institution/createInvitedInstitutionSpec.js
> +      expect(ctrl.newInstitution).toEqual(emptyInstitution);
better mock `ctrl.loadInstitution` and then do a separated test for it

2019-03-08 20:52 UTC, Luiz-FS requested changes

2019-03-08 20:52 UTC, Luiz-FS commented on frontend/institution/createInvitedInstitutionController.js
> +              return Promise.resolve();
Unnecessary promise

2019-03-08 20:52 UTC, Luiz-FS commented on frontend/institution/createInvitedInstitutionController.js
> +                  textContent: 'Estamos processando suas permissões hierárquicas. Em breve você receberá uma notificação e ficará habilitado para administrar a instituição e toda sua hierarquia na Pl
Check type of invitation to display the message or not

2019-03-14 14:25 UTC, JuliePessoa approved these changes

2019-03-14 17:10 UTC, Luiz-FS approved these changes

2019-03-14 17:17 UTC, merged