Spread push notifications throughout the app
eciis/web pull request #1522
Opened 2019-03-11 18:30 UTC by raonismaneoto

**Feature/Bug description:** 
Send a push notification every time a regular notification was sent.

**Solution:** 
Insert a push notification in the push queue in the involved handlers.

**TODO/FIXME:** n/a

2019-03-11 19:46 UTC, JuliePessoa requested changes

2019-03-11 19:46 UTC, JuliePessoa commented on backend/test/institution_handlers_tests/institution_member_handler_test.py
> +        send_email.assert_called()
duplicated?

2019-03-11 20:39 UTC, ruanres requested changes

2019-03-11 20:39 UTC, ruanres commented on backend/push_notification/push_notification_service.py
> +        """."""
remove

2019-03-11 20:39 UTC, ruanres commented on backend/push_notification/push_notification_service.py
> +        """."""
do the same to the other ones

2019-03-11 20:51 UTC, Luiz-FS approved these changes

2019-03-12 13:00 UTC, JuliePessoa approved these changes

2019-03-12 15:55 UTC, ruanres approved these changes

2019-03-12 15:55 UTC, merged