Manage institution mobile page
eciis/web pull request #1523
Opened 2019-03-11 20:08 UTC by ruanres

**Feature/Bug description:** 

**models:**

![invite-inst-model](https://user-images.githubusercontent.com/13683704/54154089-dcc3b880-441f-11e9-8928-d86b992ff20b.png)
![parent-model](https://user-images.githubusercontent.com/13683704/54154097-e0573f80-441f-11e9-807f-6fd5b07f913d.png)
![children-model](https://user-images.githubusercontent.com/13683704/54154107-e2b99980-441f-11e9-944a-86dfd36460c8.png)
![pendent-links-model](https://user-images.githubusercontent.com/13683704/54154114-e816e400-441f-11e9-92cd-6a011300081a.png)

**Solution:** 
![invite-inst](https://user-images.githubusercontent.com/13683704/54154168-0b419380-4420-11e9-9075-76d6d916092e.png)
![parent-inst](https://user-images.githubusercontent.com/13683704/54154188-1399ce80-4420-11e9-9d3f-62da203ee6b5.png)
![children-inst](https://user-images.githubusercontent.com/13683704/54154207-1e546380-4420-11e9-91c8-f45da3630f1d.gif)
![pendent-links](https://user-images.githubusercontent.com/13683704/54154216-22808100-4420-11e9-8c3c-c0c0e2761321.png)

**TODO/FIXME:** n/a

2019-03-12 12:17 UTC, tiago-lp approved these changes

2019-03-12 12:35 UTC, brobsc requested changes

2019-03-12 12:35 UTC, brobsc commented on frontend/institution/manageInstitution/management_institution_mobile.html
> +                        inviteInstHierCtrl.createIconBtn('more_vert',
Change remove link icon on superior institutions

2019-03-12 15:50 UTC, JuliePessoa requested changes

2019-03-12 15:50 UTC, JuliePessoa commented on frontend/institution/manageInstitution/management_institution_mobile.html
> +                    icon="account_balance"
icon onclick should go to institution page

2019-03-12 15:50 UTC, JuliePessoa commented on frontend/institution/manageInstitution/management_institution_mobile.html
> +                        icon="account_balance"
icon onclick should go to institution page

2019-03-12 15:50 UTC, JuliePessoa requested changes

2019-03-12 15:50 UTC, JuliePessoa commented on frontend/institution/manageInstitution/management_institution_mobile.html
> +                        icon="account_balance"
icon onclick should go to institution page

2019-03-13 14:35 UTC, JuliePessoa requested changes
green dot is missing on "Vinculos Pendentes" and "Convites Requisitados".
![image](https://user-images.githubusercontent.com/7011394/54287219-0695f000-4584-11e9-86c2-940e3bf3f242.png)

2019-03-13 20:30 UTC, JuliePessoa approved these changes

2019-03-13 20:34 UTC, merged