Hide showtoast in mobile devices
eciis/web pull request #1528
Opened 2019-03-13 15:12 UTC by MaianaB

**Feature/Bug description:** Some messages are unnecessary to show in mobile.

**Solution:** Show only error messages

**TODO/FIXME:** n/a

2019-03-13 17:37 UTC, JuliePessoa requested changes

2019-03-13 17:37 UTC, JuliePessoa commented on frontend/event/eventDetailsDirective.js
> +            MessageService.showInfoToast("O link foi copiado");
should show

2019-03-13 17:37 UTC, JuliePessoa commented on frontend/institution/institutionCardDirective.js
> +            MessageService.showInfoToast("O link foi copiado");
should show

2019-03-13 17:37 UTC, JuliePessoa commented on frontend/post/postPageController.js
> +            MessageService.showInfoToast("O link foi copiado");
should show

2019-03-13 17:54 UTC, pedroespindula requested changes

2019-03-13 17:54 UTC, pedroespindula commented on frontend/institution/transferAdminController.js
> +                MessageService.showErrorToast('Selecione um memebro!');
Typo: "Selecione um membro"

2019-03-13 17:54 UTC, pedroespindula commented on frontend/test/specs/institution/registeredInstitutionsControllerSpec.js
> +            expect(msgService.showInfoToast).toHaveBeenCalledWith('Seguindo institution');
The message that is used is right?

2019-03-13 18:59 UTC, MaianaB commented on frontend/test/specs/institution/registeredInstitutionsControllerSpec.js
> +            expect(msgService.showInfoToast).toHaveBeenCalledWith('Seguindo institution');
Yes.

2019-03-13 20:34 UTC, JuliePessoa approved these changes

2019-03-14 00:13 UTC, Luiz-FS requested changes

2019-03-14 00:13 UTC, Luiz-FS commented on feature-toggles/test/specs/utils/messageServiceSpec.js
> +            it('should not call mdToast.show', function() {
The description does not match the test

2019-03-14 00:13 UTC, Luiz-FS commented on frontend/test/specs/utils/messageServiceSpec.js
> +            it('should not call mdToast.show', function() {
The description does not match the test

2019-03-14 12:47 UTC, pedroespindula approved these changes

2019-03-14 14:38 UTC, Luiz-FS approved these changes

2019-03-14 17:16 UTC, merged