Invites mobile page
eciis/web pull request #1530
Opened 2019-03-14 13:52 UTC by ruanres

**Feature/Bug description:** Designer model
![model-invites](https://user-images.githubusercontent.com/13683704/54362081-162a3d00-4647-11e9-8fdc-e0ff7ba15efa.gif)

**Solution:** Redesigned page
![invites-page](https://user-images.githubusercontent.com/13683704/54361913-c9defd00-4646-11e9-8df2-0f761c53215d.png)
![form](https://user-images.githubusercontent.com/13683704/54361699-56d58680-4646-11e9-9c6b-15a3a7533bc4.png)
![sent-requests](https://user-images.githubusercontent.com/13683704/54361779-8a181580-4646-11e9-97f2-e3487a4c1b63.png)
![requested-invites](https://user-images.githubusercontent.com/13683704/54361797-92705080-4646-11e9-974c-2330becf3891.gif)
![accepted-requests](https://user-images.githubusercontent.com/13683704/54361809-969c6e00-4646-11e9-8aaf-ef64cdceeeba.png)

**TODO/FIXME:** n/a

2019-03-14 15:00 UTC, tiago-lp approved these changes

2019-03-14 16:27 UTC, pedroespindula requested changes

2019-03-14 16:27 UTC, pedroespindula commented on frontend/invites/inviteInstitutionController.js
> +        inviteInstCtrl.createIconBtn = (icon, color, action, params, hideBtn) => {
Can you transform this function into a factory?

2019-03-14 16:41 UTC, JuliePessoa requested changes

2019-03-14 16:41 UTC, JuliePessoa commented on frontend/invites/invite_institution_mobile.html
> +</white-toolbar>
add shadow

2019-03-14 16:41 UTC, JuliePessoa commented on frontend/invites/invite_institution_mobile.html
> +                <entity-showcase ng-repeat="acceptedInvites in inviteInstCtrl.accepted_invitations | filter: searchAcceptedInvite"
add icon onclick function to go to institution page.

2019-03-14 19:38 UTC, JuliePessoa approved these changes

2019-03-15 12:30 UTC, pedroespindula approved these changes

2019-03-15 14:59 UTC, merged