Search events
eciis/web pull request #1533
Opened 2019-03-14 18:47 UTC by tiagolimpe

**Feature/Bug description:** Creating a page to search for events.

**Solution:** 
Usage examples:
![Peek 2019-03-14 15-40](https://user-images.githubusercontent.com/20300259/54383266-6ec20000-4670-11e9-8c98-7764e80a0286.gif)
![Peek 2019-03-14 15-41222](https://user-images.githubusercontent.com/20300259/54383267-6ec20000-4670-11e9-9b5c-69daea1c8574.gif)
![Peek 2019-03-14 15-413333](https://user-images.githubusercontent.com/20300259/54383268-6f5a9680-4670-11e9-95c8-05f0a1150c00.gif)

**TODO/FIXME:** n/a

2019-03-14 19:59 UTC, MaianaB requested changes

2019-03-14 19:59 UTC, MaianaB commented on frontend/search/search_event.html
> +            ng-click="searchCtrl.hasNotSearched = true; searchCtrl.clearFilters(); searchCtrl.refreshPreviousKeyword(); searchCtrl.search_keyword = ''">
Is not better create the function?

2019-03-14 19:59 UTC, MaianaB commented on frontend/search/search_event.html
> +    <div ng-if="searchCtrl.hasNotSearched" layout="column" layout-align="center center" class="search-mobile-options" style="overflow: scroll">
move to ccs file

2019-03-15 13:11 UTC, MaianaB approved these changes

2019-03-18 18:09 UTC, Luiz-FS requested changes

2019-03-18 18:09 UTC, Luiz-FS commented on frontend/search/search.css
> +  border-color: #009688 !important;
Is really necessary?

2019-03-18 18:09 UTC, Luiz-FS commented on frontend/search/searchEventController.js
> +                refreshPreviousKeyword();
Should not be within the promise?

2019-03-18 19:17 UTC, JuliePessoa approved these changes

2019-03-18 19:29 UTC, Luiz-FS approved these changes

2019-03-18 19:38 UTC, merged