Create shared events mobile
eciis/web pull request #1534
Opened 2019-03-14 19:25 UTC by Luiz-FS

**Feature/Bug description:** Create mobile shared event screen.

**Solution:** ...

![localhost_8081_(Galaxy Note II) (3)](https://user-images.githubusercontent.com/18005317/54385458-6fa96080-4675-11e9-948f-600bd0645a34.png)
![localhost_8081_(Galaxy Note II) (5)](https://user-images.githubusercontent.com/18005317/54385466-720bba80-4675-11e9-970a-4ceb6018be33.png)

**TODO/FIXME:** n/a

2019-03-14 19:42 UTC, JuliePessoa requested changes

2019-03-14 19:42 UTC, JuliePessoa commented on frontend/event/sharedEvent.component.js
> +    app.component('sharedEvent', {
jsdoc

2019-03-14 19:42 UTC, JuliePessoa commented on frontend/event/shared_event_mobile.html
> +        <img style="width: 100%;"
move style

2019-03-14 19:42 UTC, JuliePessoa commented on frontend/event/shared_event_mobile.html
> +            <md-divider style="border: 1px; border-style: solid; width: 100%;"></md-divider>
move css style from all doc

2019-03-14 20:09 UTC, tiago-lp approved these changes

2019-03-14 20:16 UTC, brobsc approved these changes

2019-03-15 14:52 UTC, JuliePessoa approved these changes

2019-03-15 14:52 UTC, merged