Add mobile screen for invited institution creation
eciis/web pull request #1535
Opened 2019-03-14 20:39 UTC by brobsc

**Feature/Bug description:** New design requires new screens for creating a invited institution

**Solution:** Add new screens, creating three new form components, a new controller and new conditional template (on creation prompt)

**TODO/FIXME:** n/a

2019-03-15 19:55 UTC, Luiz-FS requested changes

2019-03-15 19:55 UTC, Luiz-FS commented on frontend/institution/createInvitedInstitutionController.js
> +              'A instituição foi criada e ja se encontra habilitada na Plataforma Virtual CIS.'
e `já` se encontra

2019-03-15 20:00 UTC, Luiz-FS requested changes
![Captura de tela de 2019-03-15 16-48-28](https://user-images.githubusercontent.com/18005317/54458753-8ae2a180-4743-11e9-8765-4bcaeab8dd61.png)

When the user finish creating a new institution by invitation, returns to the initial screen to accept the invitation.

![Captura de tela de 2019-03-15 16-55-19](https://user-images.githubusercontent.com/18005317/54458765-91711900-4743-11e9-85e5-a1ab4059aeed.png)

2019-03-18 14:22 UTC, Luiz-FS approved these changes

2019-03-18 19:13 UTC, JuliePessoa approved these changes

2019-03-18 19:13 UTC, merged