Redesigning the modal to alert about existing institutions
eciis/web pull request #1546
Opened 2019-03-19 19:47 UTC by tiagolimpe

**Feature/Bug description:** 
The current screen is out of date with the new design.
![Selection_002](https://user-images.githubusercontent.com/20300259/54637050-87faf000-4a66-11e9-879a-bb002f763634.png)

**Solution:** 
I used generic components to show the modal according to the new design.
![Selection_001](https://user-images.githubusercontent.com/20300259/54637108-a6f98200-4a66-11e9-949d-650892f03a18.png)

**TODO/FIXME:** n/a

2019-03-19 21:05 UTC, pedroespindula approved these changes

2019-03-20 18:02 UTC, JuliePessoa requested changes

2019-03-20 18:02 UTC, JuliePessoa commented on frontend/invites/inviteInstitutionController.js
> +                    'app/invites/existing_institutions_mobile.html', 475),
use SCREEN_SIZE constant

2019-03-20 20:16 UTC, JuliePessoa requested changes

2019-03-20 20:16 UTC, JuliePessoa commented on frontend/invites/existing_institutions_mobile.html
> +            title="institution.name"
make the font size smaller

2019-03-20 20:16 UTC, JuliePessoa commented on frontend/invites/existing_institutions_mobile.html
> +            avatar="institution.photo_url"
make the avatar smaller

2019-03-25 18:52 UTC, JuliePessoa approved these changes

2019-03-25 18:52 UTC, merged